<?
class EntityFactory_pokemon extends EntityFactory_combo
{
	static $type='pokemon';
	static $behavior='pokemon';	

	static $model=array(
		'basic_form'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_basic_form_of_pokemon_A'
			),
		'stage'=>array(
			'table'=>'pokemon_main',
			'type'=>'natural'
			),
		'name_eng'=>array(
			'table'=>'pokemon_main',
			'type'=>'name',
			'lang'=>'eng'
			),
		'name_rus'=>array(
			'table'=>'pokemon_main',
			'type'=>'name',
			'lang'=>'rus'
			),
		'name_jap'=>array(
			'table'=>'pokemon_main',
			'type'=>'name',
			'lang'=>'jap'
			),
		'name_jap_kana'=>array(
			'table'=>'pokemon_main',
			'type'=>'name',
			'lang'=>'jap_kana'
			),
		'nickname_rus'=>array(
			'table'=>'pokemon_main',
			'type'=>'name',
			'lang'=>'rus'
			),	
		'nickname_eng'=>array(
			'table'=>'pokemon_main',
			'type'=>'name',
			'lang'=>'eng'
			),	
		'official'=>array(
			'type'=>'bool'
			),
		'type1'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_battle_type_of_pokemon_A',
			'method'=>'qlink',
			'default'=>array('ord'=>1)
			),
		'type2'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_battle_type_of_pokemon_A',
			'method'=>'qlink',
			'default'=>array('ord'=>2)
			),
		'height'=>array(
			'table'=>'pokemon_main',
			'type'=>'real'
			),
		'weight'=>array(
			'table'=>'pokemon_main',
			'type'=>'real'
			),
		'height'=>array(
			'table'=>'pokemon_main',
			'type'=>'real'
			),
		'area_group'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_area_group_of_pokemon_A',
			'method'=>'qlink'
			),			
		'body_group'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_body_type_of_pokemon_A',
			'method'=>'qlink'
			),			
		'breeding_group1'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_breeding_group_of_pokemon_A',
			'method'=>'qlink',
			'default'=>array('ord'=>1)
			),			
		'breeding_group2'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_breeding_group_of_pokemon_A',
			'method'=>'qlink',
			'default'=>array('ord'=>2)
			),
		'females'=>array(
			'table'=>'pokemon_main',
			'type'=>'female_ratio'
			),
		'color'=>array(
			'table'=>'pokemon_main',
			'type'=>'B_is_color_of_pokemon_A'
			),
		'base_hp'=>array(
			'table'=>'pokemon_main',
			'type'=>'base_stat',
			'stat'=>'hp'
			),
		'base_att'=>array(
			'table'=>'pokemon_main',
			'type'=>'base_stat',
			'stat'=>'att'
			),			
		'base_def'=>array(
			'table'=>'pokemon_main',
			'type'=>'base_stat',
			'stat'=>'def'
			),			
		'base_sp_att'=>array(
			'table'=>'pokemon_main',
			'type'=>'base_stat',
			'stat'=>'sp_att'
			),			
		'base_sp_def'=>array(
			'table'=>'pokemon_main',
			'type'=>'base_stat',
			'stat'=>'sp_def'
			),			
		'base_speed'=>array(
			'table'=>'pokemon_main',
			'type'=>'base_stat',
			'stat'=>'speed'
			),
		'effort_hp'=>array(
			'table'=>'pokemon_main',
			'type'=>'effort_stat',
			'stat'=>'hp'
			),
		'effort_att'=>array(
			'table'=>'pokemon_main',
			'type'=>'effort_stat',
			'stat'=>'att'
			),			
		'effort_def'=>array(
			'table'=>'pokemon_main',
			'type'=>'effort_stat',
			'stat'=>'def'
			),			
		'effort_sp_att'=>array(
			'table'=>'pokemon_main',
			'type'=>'effort_stat',
			'stat'=>'sp_att'
			),			
		'effort_sp_def'=>array(
			'table'=>'pokemon_main',
			'type'=>'effort_stat',
			'stat'=>'sp_def'
			),			
		'effort_speed'=>array(
			'table'=>'pokemon_main',
			'type'=>'effort_stat',
			'stat'=>'speed'
			),
		'pic_mini'=>array(
			'table'=>'pokemon_main',
			'type'=>'icon',
			'field'=>'B_is_icon_for_pokemon_A',
			'method'=>'qlink'
			),
		'pic_sprite'=>array(
			'table'=>'pokemon_main',
			'type'=>'sprite',
			'field'=>'B_is_sprite_for_pokemon_A',
			'method'=>'qlink'
			),
		'pic_art'=>array(
			'table'=>'pokemon_main',
			'type'=>'art',
			'field'=>'B_is_art_for_pokemon_A',
			'method'=>'qlink'
			),
		'naming'=>array(
			'table'=>'pokemon_main',
			'type'=>'text',
			),
		'base_EXP'=>array(
			'table'=>'pokemon_main',
			'type'=>'EXP',
			),		
		'full_growth_EXP'=>array(
			'table'=>'pokemon_main',
			'type'=>'EXP',
			),		
		'growth_rate'=>array(
			'table'=>'pokemon_main',
			'type'=>'pokemon_growth',
			),
		'egg_steps'=>array(
			'table'=>'pokemon_main',
			'type'=>'game_distance',
			),
		'catch_rate'=>array(
			'table'=>'pokemon_main',
			'type'=>'pokemon_catch_rate',
			),
		'attacks'=>array(
			'type'=>'B_is_attack_of_pokemon_A',
			'list'=>1,
			'list_entity'=>'attacks_list'
		)
	);
}
?>